version: "3"
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    tty: true
    stdin_open: true
    depends_on:
      - db
    # ports:
    #   - "3000:3000"
    volumes:
      - .:/my_app
      # - public-data:/my_app/public
      # - tmp-data:/my_app/tmp
      # - log-data:/my_app/log
  nginx:
    build:
      context: containers/nginx
    volumes:
      - .:/my_app
      # - public-data:/my_app/public
      # - tmp-data:/my_app/tmp
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  # public-data:
  # tmp-data:
  # log-data:
  postgres_data: