version: "3"
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
    depends_on:
      - db
    volumes:
      - .:/my_app
  nginx:
    build:
      context: containers/nginx
    volumes:
      - .:/my_app
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  postgres_data: